# Generated by Django 3.1.3 on 2020-11-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servicerank_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerank',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranks', to='app.service'),
        ),
    ]
